version: 0.2

phases:
  install:
    commands:
      - echo Entering Install Phase...
  pre_build:
    commands:
      - echo Entering pre_build Phase...
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - mvn exec:java -Dexec.classpathScope=test  -Dexec.mainClass=io.cucumber.core.cli.Main  -Dexec.args="src/test/resources"
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
  - '**/*'