version: 0.2
#
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - echo Running tests for surefire junit
      - mvn test -f surefire/pom.xml -fn
reports:
 group2-bdd-new:
   files:
     - '**/*'
   base-directory: 'target/surefire-reports/'
reports:
  group2-bdd-new:
    files:
      - "target/surefire-reports/*.xml"
    file-format: "JUNITXML"
artifacts:
  files:
    - '**/*'