version: 0.2

phases:
  install:
    commands:
      - echo Entering Install Phase...
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Entering pre_build phase...
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - ./mvnw clean install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - application.jar