version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Entering Install Phase...
  pre_build:
    commands:
      - echo Entering pre_build phase...
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  type: zip
  name: application